# Generated by Django 4.0.5 on 2022-09-28 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=1000000)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
